name: Pull Request CI

on: push

jobs:
    build_and_test:
        name: Build and Test

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: XO Linter
              run: pnpm run lint:ci

            - name: Prettier Formatter
              run: pnpm run prettier:ci

            - name: Start Docker Test Environment
              run: docker compose up -d

            - name: Jest Tests
              id: jest_test
              run:
                  pnpm run test:ci

                  # - name: Upload Jest Test Artifacts
                  #   uses: actions/upload-artifact@v3
                  #   if: steps.jest_test.conclusion != 'skipped'
                  #   with:
                  #       name: jest-test-report
                  #       path: junit.xml

                  # - name: Upload Coverage Artifacts
                  #   uses: actions/upload-artifact@v3
                  #   if: steps.jest_test.conclusion != 'skipped'
                  #   with:
                  #       name: coverage-report
                  #       path: coverage

            - name: Stop Docker Test Environment
              run: docker compose down

            - name: Build project
              run: npm run build
